/* msgBlpscuDef.c - Declaration of the BLPSCU control unit messages */

/* Copyright - Ion Beam Applications */

/*
Modification History
--------------------
swelsch,13Feb2009 : Creation

*/

/*
DESCRIPTION
Declaration of the message array.
  EXAMPLES: Here is a small example describing
            the use of MSG_DEF stucture.
  msg[3].ptr_table[0] =
          TdaqVarLookup( msg[3].var_names[0] );
  => bind the first pointer of message #4 to
     his related .sdb variable
*/


#include "msgDef.h"
#include "msgBlpscuDef.h"

/* Globals */

/*
 * Definition of variable names that are
 * located in the .sdb file.
 * There is one line per message type.
 */

/* DB50: Copy of Mementos from M64.0 to M87.4 */
SDB_VARIABLE blpscu_db50_boolean[] =      /* DB 50 */
{
"mcr_blpscu.b2e.status",
"mcr_blpscu.b1e.status",
"mcr_blpscu.smps.sm30hz_waterflow",
"mcr_blpscu.smps.sm30hz_thermalsw",
"mcr_blpscu.smps.sm3hz_waterflow",
"mcr_blpscu.smps.sm3hz_thermalsw",
"mcr_blpscu.smps.onreq",
"mcr_blpscu.smps.status",		/*64.0*/
"dummy",
"dummy",
"mcr_blpscu.b2b2.status",
"mcr_blpscu.b1b2.status",
"mcr_blpscu.b2b1.status",
"mcr_blpscu.b1b1.status",
"mcr_blpscu.b4e.status",
"mcr_blpscu.b3e.status",		/*65.0*/
"dummy",
"dummy",
"mcr_blpscu.b1f1.status",
"mcr_blpscu.b1g2.status",		/*66.4*/
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.q1b2.status",
"mcr_blpscu.q1b1.status",
"mcr_blpscu.q10e.status",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.b2g2.status",		/*67.0*/
"dummy",
"dummy",
"mcr_blpscu.q6s1.status",
"mcr_blpscu.q1s1.status",
"mcr_blpscu.q1f1.status",
"mcr_blpscu.q1e.status",		/*68.2*/
"dummy",
"dummy",
"mcr_blpscu.q2s1.status",
"mcr_blpscu.q2f1.status",
"mcr_blpscu.q2e.status",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.q2b2.status",
"mcr_blpscu.q2b1.status",		/*69.0*/
"dummy",
"dummy",
"dummy",
"mcr_blpscu.q3b2.status",
"mcr_blpscu.q3b1.status",
"dummy",
"mcr_blpscu.q7s1.status",		/*70.1*/
"dummy",
"mcr_blpscu.q4s1.status",
"mcr_blpscu.q4e.status",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.q3s1.status",
"mcr_blpscu.q3f1.status",
"mcr_blpscu.q3e.status",		/*71.0*/
"dummy",
"dummy",
"dummy",
"mcr_blpscu.q1g2.status",
"mcr_blpscu.q5e.status",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.q2g2.status",
"mcr_blpscu.q6e.status",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.q5s1.status",		/*73.0*/
"mcr_blpscu.q4g2.status",
"mcr_blpscu.q8e.status",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.q3g2.status",
"mcr_blpscu.q7e.status",
"dummy",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.q5g2.status",		/*75.4*/
"mcr_blpscu.q9e.status",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.sltr1_valve.open_enabled",
"mcr_blpscu.bltr1_valve.open_enabled",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.t1b1.status",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.bltr2_valve.open_enabled",
"dummy",
"dummy",
"mcr_blpscu.t1g2.status",
"mcr_blpscu.t1f1.status",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.t1b2.status",		/*78.0*/
"dummy",
"mcr_blpscu.t2f1.status",
"mcr_blpscu.t2e.status",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.t1s1.status",
"dummy",
"dummy",
"mcr_blpscu.t3s1.status",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.t2s1.status",
"dummy",
"dummy",
"mcr_blpscu.trb2b1.status",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.trb1b2.status",
"mcr_blpscu.trb1b1.status",
"dummy",
"dummy",
"mcr_blpscu.beamline1.ps_selection_enabled",
"mcr_blpscu.smps.status",
"mcr_blpscu.trb4e.status",
"mcr_blpscu.trb3e.status",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.trb2b2.status",		/*82.0*/
"dummy",
"dummy",
"mcr_blpscu.sw_beamline2.selected",
"mcr_blpscu.sw_beamline1.selected",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.beamline2.ps_selection_enabled",	/*83.0*/
"dummy",
"mcr_blpscu.b12b2.status",
"mcr_blpscu.b12b1.status",
"mcr_blpscu.trb34e.status",
"mcr_blpscu.b1234e.status",
"mcr_blpscu.q56e.status",
"mcr_blpscu.q47e.status",			/*84.1*/
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.smps.internalok",
"mcr_blpscu.t2g2.status",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.smps.standby",		/*86.2*/
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.td_sg_rec.status",		/*87.4*/
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
NULL
};

/* DB60: Copy of Mementos from I14 to I45 */
SDB_VARIABLE blpscu_db60_boolean[] =         /* DB 60 */
{                                         
"mcr_blpscu.q2f1.thermalsw",
"mcr_blpscu.q1f1.thermalsw",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",				/*12.0*/
"mcr_blpscu.q1g2.thermalsw",
"mcr_blpscu.b1f1.waterflow",
"mcr_blpscu.b1f1.thermalsw",
"dummy",
"mcr_blpscu.q3f1.waterflow",
"mcr_blpscu.q2f1.waterflow",
"mcr_blpscu.q1f1.waterflow",
"mcr_blpscu.q3f1.thermalsw",		/*13.0*/
"mcr_blpscu.q2i2.waterflow",
"dummy",
"mcr_blpscu.q3g2.waterflow",
"mcr_blpscu.q2g2.waterflow",
"mcr_blpscu.q1g2.waterflow",
"dummy",
"mcr_blpscu.q3g2.thermalsw",
"mcr_blpscu.q2g2.thermalsw",		/*14.0*/
"mcr_blpscu.b2g2.thermalsw",
"mcr_blpscu.q5g2.waterflow",
"mcr_blpscu.q4g2.waterflow",
"mcr_blpscu.q5g2.thermalsw",
"mcr_blpscu.q4g2.thermalsw",
"mcr_blpscu.b1g2.waterflow",
"mcr_blpscu.b1g2.thermalsw",
"mcr_blpscu.q3i2.waterflow",		/*15.0*/
"mcr_blpscu.tr2_sm.sm3hz_waterflow",
"mcr_blpscu.tr2_sm.sm30hz_thermalsw",
"mcr_blpscu.tr2_sm.sm3hz_thermalsw",
"mcr_blpscu.xray_tr2.thermalsw",
"mcr_blpscu.q2n2.thermalsw",
"mcr_blpscu.q12n2.waterflow",
"mcr_blpscu.q1n2.thermalsw",
"mcr_blpscu.b2g2.waterflow",		/*16.0*/
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.tr2_sm.sm30hz_waterflow",	/*17.0*/
"mcr_blpscu.q1e.thermalsw",
"dummy",
"mcr_blpscu.scm_swc.thermalsw",
"mcr_blpscu.ra1_valve.closed",
"mcr_blpscu.ra1_valve.opened",
"mcr_blpscu.q4f1.thermalsw",
"dummy",
"dummy",
"mcr_blpscu.q4e.thermalsw",
"mcr_blpscu.b1e.waterflow",
"mcr_blpscu.b1234e.thermalsw",
"mcr_blpscu.q3e.waterflow",
"mcr_blpscu.q2e.waterflow",
"mcr_blpscu.q1e.waterflow",
"mcr_blpscu.q3e.thermalsw",
"mcr_blpscu.q2e.thermalsw",		/*19.0*/
"mcr_blpscu.b2e.waterflow",
"mcr_blpscu.q7e.waterflow",
"mcr_blpscu.q6e.waterflow",
"mcr_blpscu.q5e.waterflow",
"mcr_blpscu.q4e.waterflow",
"mcr_blpscu.q7e.thermalsw",
"mcr_blpscu.q6e.thermalsw",
"mcr_blpscu.q5e.thermalsw",		/*20.0*/
"mcr_blpscu.q10e.waterflow",
"mcr_blpscu.q9e.waterflow",
"mcr_blpscu.q8e.waterflow",
"mcr_blpscu.q10e.thermalsw",
"mcr_blpscu.q9e.thermalsw",
"mcr_blpscu.q8e.thermalsw",
"mcr_blpscu.b4e.waterflow",
"mcr_blpscu.b3e.waterflow",
"mcr_blpscu.fbtr1_valve.closed",
"mcr_blpscu.fbtr1_valve.opened",
"mcr_blpscu.q3b1.waterflow",
"mcr_blpscu.q2b1.waterflow",
"mcr_blpscu.q1b1.waterflow",
"mcr_blpscu.q3b1.thermalsw",
"mcr_blpscu.q2b1.thermalsw",
"mcr_blpscu.q1b1.thermalsw",		/*22.0*/
"mcr_blpscu.q5s1.thermalsw",
"mcr_blpscu.q4s1.thermalsw",
"mcr_blpscu.q3s1.thermalsw",
"mcr_blpscu.q2s1.thermalsw",
"mcr_blpscu.q1s1.thermalsw",
"mcr_blpscu.b2b1.waterflow",
"mcr_blpscu.b1b1.waterflow",
"mcr_blpscu.b12b1.thermalsw",
"mcr_blpscu.q1b2.thermalsw",
"mcr_blpscu.sltr1_valve.closed",
"mcr_blpscu.sltr1_valve.opened",
"mcr_blpscu.q5s1.waterflow",
"mcr_blpscu.q4s1.waterflow",
"mcr_blpscu.q3s1.waterflow",
"mcr_blpscu.q2s1.waterflow",
"mcr_blpscu.q1s1.waterflow",
"mcr_blpscu.b12b2.thermalsw",
"mcr_blpscu.gtr2_valve.closed",
"mcr_blpscu.gtr2_valve.opened",
"mcr_blpscu.q3b2.waterflow",
"mcr_blpscu.q2b2.waterflow",
"mcr_blpscu.q1b2.waterflow",
"mcr_blpscu.q3b2.thermalsw",
"mcr_blpscu.q2b2.thermalsw",		/*25.0*/
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.b2b2.waterflow",
"mcr_blpscu.b1b2.waterflow",		/*26.0*/
"dummy",
"dummy",
"mcr_blpscu.smps.internalok",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"mcr_blpscu.q7s1.waterflow",
"mcr_blpscu.q6s1.waterflow",
"mcr_blpscu.q7s1.thermalsw",
"mcr_blpscu.q6s1.thermalsw",		/*28.1*/
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
"dummy",
NULL
};	

/* DB80: ps Variables.  from DBX0.0 to DBX118.7 */
SDB_VARIABLE blpscu_db80_boolean[] =         /* DB 80 */
{                                         /* add 0 */
"mcr_blpscu.q2e.internalok",
"mcr_blpscu.q1e.ctrlmode",
"mcr_blpscu.q1e.regulok",
"mcr_blpscu.q1e.internalok",
"mcr_blpscu.trim_unit.internalok",
"mcr_blpscu.steering_unit.internalok",
"mcr_blpscu.quad_unit.internalok",
"mcr_blpscu.dipole_unit.internalok",
"mcr_blpscu.q47e.ctrlmode",
"mcr_blpscu.q47e.regulok",
"mcr_blpscu.q47e.internalok",
"mcr_blpscu.q3e.ctrlmode",
"mcr_blpscu.q3e.regulok",
"mcr_blpscu.q3e.internalok",
"mcr_blpscu.q2e.ctrlmode",
"mcr_blpscu.q2e.regulok",
"mcr_blpscu.q7e.ctrlmode",
"mcr_blpscu.q7e.regulok",
"mcr_blpscu.q7e.internalok",
"mcr_blpscu.q4e.ctrlmode",
"mcr_blpscu.q4e.regulok",
"mcr_blpscu.q4e.internalok",
"mcr_blpscu.q47e.thermalsw",
"mcr_blpscu.q47e.waterflow",
"mcr_blpscu.q5e.ctrlmode",
"mcr_blpscu.q5e.regulok",
"mcr_blpscu.q5e.internalok",
"mcr_blpscu.q56e.thermalsw",
"mcr_blpscu.q56e.waterflow",
"mcr_blpscu.q56e.ctrlmode",
"mcr_blpscu.q56e.regulok",
"mcr_blpscu.q56e.internalok",
"mcr_blpscu.q9e.regulok",
"mcr_blpscu.q9e.internalok",
"mcr_blpscu.q8e.ctrlmode",
"mcr_blpscu.q8e.regulok",
"mcr_blpscu.q8e.internalok",
"mcr_blpscu.q6e.ctrlmode",
"mcr_blpscu.q6e.regulok",
"mcr_blpscu.q6e.internalok",
"mcr_blpscu.b1234e.waterflow",
"mcr_blpscu.b1234e.ctrlmode",
"mcr_blpscu.b1234e.regulok",
"mcr_blpscu.b1234e.internalok",
"mcr_blpscu.q10e.ctrlmode",
"mcr_blpscu.q10e.regulok",
"mcr_blpscu.q10e.internalok",
"mcr_blpscu.q9e.ctrlmode",
"mcr_blpscu.b2e.thermalsw",
"mcr_blpscu.b2e.ctrlmode",
"mcr_blpscu.b2e.regulok",
"mcr_blpscu.b2e.internalok",
"mcr_blpscu.b1e.thermalsw",
"mcr_blpscu.b1e.ctrlmode",
"mcr_blpscu.b1e.regulok",
"mcr_blpscu.b1e.internalok",
"mcr_blpscu.b4e.thermalsw",
"mcr_blpscu.b4e.ctrlmode",
"mcr_blpscu.b4e.regulok",
"mcr_blpscu.b4e.internalok",
"mcr_blpscu.b3e.thermalsw",
"mcr_blpscu.b3e.ctrlmode",
"mcr_blpscu.b3e.regulok",
"mcr_blpscu.b3e.internalok",
"mcr_blpscu.q3b1.regulok",
"mcr_blpscu.q3b1.internalok",
"mcr_blpscu.q2b1.ctrlmode",
"mcr_blpscu.q2b1.regulok",
"mcr_blpscu.q2b1.internalok",
"mcr_blpscu.q1b1.ctrlmode",
"mcr_blpscu.q1b1.regulok",
"mcr_blpscu.q1b1.internalok",
"mcr_blpscu.q3f1.internalok",
"mcr_blpscu.q2f1.ctrlmode",
"mcr_blpscu.q2f1.regulok",
"mcr_blpscu.q2f1.internalok",
"mcr_blpscu.q1f1.ctrlmode",
"mcr_blpscu.q1f1.regulok",
"mcr_blpscu.q1f1.internalok",
"mcr_blpscu.q3b1.ctrlmode",
"mcr_blpscu.b12b1.ctrlmode",
"mcr_blpscu.b12b1.regulok",
"mcr_blpscu.b12b1.internalok",
"mcr_blpscu.b1f1.ctrlmode",
"mcr_blpscu.b1f1.regulok",
"mcr_blpscu.b1f1.internalok",
"mcr_blpscu.q3f1.ctrlmode",
"mcr_blpscu.q3f1.regulok",
"mcr_blpscu.b2b1.ctrlmode",
"mcr_blpscu.b2b1.regulok",
"mcr_blpscu.b2b1.internalok",
"mcr_blpscu.b1b1.thermalsw",
"mcr_blpscu.b1b1.ctrlmode",
"mcr_blpscu.b1b1.regulok",
"mcr_blpscu.b1b1.internalok",
"mcr_blpscu.b12b1.waterflow",
"mcr_blpscu.q3s1.internalok",
"mcr_blpscu.q2s1.ctrlmode",
"mcr_blpscu.q2s1.regulok",
"mcr_blpscu.q2s1.internalok",
"mcr_blpscu.q1s1.ctrlmode",
"mcr_blpscu.q1s1.regulok",
"mcr_blpscu.q1s1.internalok",
"mcr_blpscu.b2b1.thermalsw",
"mcr_blpscu.q5s1.ctrlmode",
"mcr_blpscu.q5s1.regulok",
"mcr_blpscu.q5s1.internalok",
"mcr_blpscu.q4s1.ctrlmode",
"mcr_blpscu.q4s1.regulok",
"mcr_blpscu.q4s1.internalok",
"mcr_blpscu.q3s1.ctrlmode",
"mcr_blpscu.q3s1.regulok",
"mcr_blpscu.q1b2.regulok",
"mcr_blpscu.q1b2.internalok",
"mcr_blpscu.q7s1.ctrlmode",
"mcr_blpscu.q7s1.regulok",
"mcr_blpscu.q7s1.internalok",
"mcr_blpscu.q6s1.ctrlmode",
"mcr_blpscu.q6s1.regulok",
"mcr_blpscu.q6s1.internalok",
"mcr_blpscu.b12b2.internalok",
"mcr_blpscu.q3b2.ctrlmode",
"mcr_blpscu.q3b2.regulok",
"mcr_blpscu.q3b2.internalok",
"mcr_blpscu.q2b2.ctrlmode",
"mcr_blpscu.q2b2.regulok",
"mcr_blpscu.q2b2.internalok",
"mcr_blpscu.q1b2.ctrlmode",
"mcr_blpscu.b2b2.internalok",
"mcr_blpscu.b1b2.thermalsw",
"mcr_blpscu.b1b2.ctrlmode",
"mcr_blpscu.b1b2.regulok",
"mcr_blpscu.b1b2.internalok",
"mcr_blpscu.b12b2.waterflow",
"mcr_blpscu.b12b2.ctrlmode",
"mcr_blpscu.b12b2.regulok",
"mcr_blpscu.q2g2.regulok",
"mcr_blpscu.q2g2.internalok",
"mcr_blpscu.q1g2.ctrlmode",
"mcr_blpscu.q1g2.regulok",
"mcr_blpscu.q1g2.internalok",
"mcr_blpscu.b2b2.thermalsw",
"mcr_blpscu.b2b2.ctrlmode",
"mcr_blpscu.b2b2.regulok",
"mcr_blpscu.q5g2.internalok",
"mcr_blpscu.q4g2.ctrlmode",
"mcr_blpscu.q4g2.regulok",
"mcr_blpscu.q4g2.internalok",
"mcr_blpscu.q3g2.ctrlmode",
"mcr_blpscu.q3g2.regulok",
"mcr_blpscu.q3g2.internalok",
"mcr_blpscu.q2g2.ctrlmode",
"mcr_blpscu.b2g2.ctrlmode",
"mcr_blpscu.b2g2.regulok",
"mcr_blpscu.b2g2.internalok",
"mcr_blpscu.b1g2.ctrlmode",
"mcr_blpscu.b1g2.regulok",
"mcr_blpscu.b1g2.internalok",
"mcr_blpscu.q5g2.ctrlmode",
"mcr_blpscu.q5g2.regulok",
"dummy",
"mcr_blpscu.tr2_sm.selected",
"mcr_blpscu.q2n2.ctrlmode",
"mcr_blpscu.q2n2.regulok",
"mcr_blpscu.q2n2.internalok",
"mcr_blpscu.q1n2.ctrlmode",
"mcr_blpscu.q1n2.regulok",
"mcr_blpscu.q1n2.internalok",
NULL
};

/* DB90 video : from DBB0 to DBB118 */
SDB_VARIABLE blpscu_db90_8bit[] =         /* DB 90 */
{                                         /* add 0 */
"mcr_blpscu.dipole.video",
"mcr_blpscu.quad.video",
"mcr_blpscu.steering.video",
"mcr_blpscu.trim.video",
"mcr_blpscu.smps.video",
"mcr_blpscu.q1e.video",
"mcr_blpscu.q2e.video",
"mcr_blpscu.q3e.video",
"mcr_blpscu.q47e.video",
"mcr_blpscu.q4e.video",
"mcr_blpscu.q7e.video",
"mcr_blpscu.q56e.video",
"mcr_blpscu.q5e.video",
"mcr_blpscu.q6e.video",
"mcr_blpscu.q8e.video",
"mcr_blpscu.q9e.video",
"mcr_blpscu.q10e.video",
"mcr_blpscu.b1234e.video",
"mcr_blpscu.b1e.video",
"mcr_blpscu.b2e.video",
"mcr_blpscu.b3e.video",
"mcr_blpscu.b4e.video",
"mcr_blpscu.t2e.video",
"mcr_blpscu.trb34e.video",
"mcr_blpscu.trb3e.video",
"mcr_blpscu.trb4e.video",
"mcr_blpscu.q1b1.video",
"mcr_blpscu.q2b1.video",
"mcr_blpscu.q3b1.video",
"mcr_blpscu.q1f1.video",
"mcr_blpscu.q2f1.video",
"mcr_blpscu.q3f1.video",
"mcr_blpscu.b1f1.video",
"mcr_blpscu.b12b1.video",
"mcr_blpscu.b1b1.video",
"mcr_blpscu.b2b1.video",
"mcr_blpscu.t1f1.video",
"mcr_blpscu.trb2b1.video",
"mcr_blpscu.q1s1.video",
"mcr_blpscu.q2s1.video",
"mcr_blpscu.q3s1.video",
"mcr_blpscu.q4s1.video",
"mcr_blpscu.q5s1.video",
"mcr_blpscu.q6s1.video",
"mcr_blpscu.q7s1.video",
"mcr_blpscu.t1s1.video",
"mcr_blpscu.t2s1.video",
"mcr_blpscu.t3s1.video",
"mcr_blpscu.trb1b1.video",
"mcr_blpscu.q1b2.video",
"mcr_blpscu.q2b2.video",
"mcr_blpscu.q3b2.video",
"mcr_blpscu.b12b2.video",
"mcr_blpscu.b1b2.video",
"mcr_blpscu.b2b2.video",
"mcr_blpscu.t1b2.video",
"mcr_blpscu.q1g2.video",
"mcr_blpscu.q2g2.video",
"mcr_blpscu.q3g2.video",
"mcr_blpscu.q4g2.video",
"mcr_blpscu.q5g2.video",
"mcr_blpscu.b1g2.video",
"mcr_blpscu.b2g2.video",
"mcr_blpscu.t1g2.video",
"mcr_blpscu.t2g2.video",
"mcr_blpscu.trb2b2.video",
"mcr_blpscu.q1n2.video",
"mcr_blpscu.q2n2.video",
"mcr_blpscu.modular.video",
NULL
};

/* DB01 INT values */
SDB_VARIABLE blpscu_db81_real32[] =           /* DB    1 */
{                                         /* add 0 */
¡°mcr_blpscu.sw.counter¡±,
NULL
};

/* DB01 INT values */
SDB_VARIABLE blpscu_sw_counter[] =           /* DB    1 */
{                                         /* add 0 */
"mcr_blpscu.sw.counter",
NULL
};

/* Construction of the msg.(one line per Message) */
MSG_DEF blpscuMsg[] =
{
 {BLPSCU_DB50_BOOLEAN,    {},     blpscu_db50_boolean,  _BOOLEAN,  192, 50,  64},
 {BLPSCU_DB60_BOOLEAN,    {},     blpscu_db60_boolean,  _BOOLEAN,  256, 60,  14},
 {BLPSCU_DB80_BOOLEAN,    {},     blpscu_db80_boolean,  _BOOLEAN,  296, 80,   0},
 {BLPSCU_DB81_REAL32,     {},     blpscu_db81_real32,     _FLOAT,    8, 81,   0}, 
 {BLPSCU_DB90_BYTE,       {},        blpscu_db90_8bit,     _BYTE,  126, 90,   0},
 {BLPSCU_SW_COUNTER,      {},        blpscu_sw_counter,  _UINT16,    1,  1,   0},
 {NO_MORE_NAME}
};

